### ISSUE TITLE
Error importing version 0.3.0

### ISSUE THREAD

**Issue by alxdncn** [Looking-Glass/blenderLKG#34]
When I attempted to import the add-on, I got this error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\looking_glass_tools\__init__.py", line 49, in <module>
    raise Exception(message)
Exception: 

The Looking Glass Toolset addon cannot be registered correctly.
Please try to remove and install it again.
If it still does not work, report it.

**Comment by GottfriedHofmann** [comment]
Did you try to re-install the addon? I tested the installation on two different Windows 10 machines and it worked for me.

**Comment by GottfriedHofmann** [comment]
Oh, it seems like you are trying to use the addon with Blender 2.83 - can you try again with Blender 2.92?

**Comment by alxdncn** [comment]
Ah right you are - will try again!
